#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin; adapted for dual layout.
# Build: compile src/ → lib/ (host via tsc) + client bundle via tsdown.
#
# Supports BOTH layouts (auto-detected):
#   1. SOURCE checkout    — marker: <checkout>/packages        (dev machines)
#   2. INSTALLED checkout — marker: <checkout>/node_modules/@deepseek-ai/dsh-tools
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# DSH_CHECKOUT 探测：环境变量 → 常见路径（home 下 dsh-harness / 全局 dsh 安装）
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in \
    "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness" \
    "$(dirname "$(dirname "$(command -v dsh 2>/dev/null || true)")")" \
    "${DSH_GLOBAL_DIR:-}" ; do
    [ -n "$candidate" ] && { [ -d "$candidate/packages" ] || [ -e "$candidate/node_modules/@deepseek-ai/dsh-tools" ]; } && { CHECKOUT="$candidate"; break; }
  done
fi
if [ -z "$CHECKOUT" ] && [ -n "${NVM_DIR:-}" ]; then
  for v in "$NVM_DIR"/versions/node/*/lib/node_modules/@deepseek-ai/dsh; do
    [ -e "$v/node_modules/@deepseek-ai/dsh-tools" ] && { CHECKOUT="$v"; break; }
  done
fi
if [ -z "$CHECKOUT" ] || { [ ! -d "$CHECKOUT/packages" ] && [ ! -e "$CHECKOUT/node_modules/@deepseek-ai/dsh-tools" ]; }; then
  echo "build: cannot locate a dsh checkout/install (set DSH_CHECKOUT)" >&2
  exit 1
fi

if [ -d "$CHECKOUT/packages" ]; then LAYOUT=source; else LAYOUT=installed; fi

if   [ -x "$CHECKOUT/node_modules/.bin/tsc" ]; then TSC="$CHECKOUT/node_modules/.bin/tsc"
elif [ -x "$ROOT/node_modules/.bin/tsc" ];    then TSC="$ROOT/node_modules/.bin/tsc"
else echo "build: tsc not found (checkout or local devDependencies)" >&2; exit 1
fi

link_pkg() {
  local link="node_modules/$1"
  local target="$2"
  if [ ! -e "$target" ]; then
    echo "build: dependency target missing: $target" >&2
    exit 1
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "$link" "$target"
}

echo "=== Linking build dependencies (layout: $LAYOUT, checkout: $CHECKOUT) ==="
mkdir -p node_modules/@deepseek-ai
node -e "const fs=require('fs');fs.rmSync('node_modules/@standard-schema',{recursive:true,force:true})"

if [ "$LAYOUT" = source ]; then
  link_pkg cordis vendor/cordis
  link_pkg cosmokit vendor/cosmokit
  link_pkg schemastery vendor/schemastery
  link_pkg @deepseek-ai/dsh-tools packages/core/tools
  link_pkg @deepseek-ai/dsh-llm packages/llm/llm
  link_pkg @types/node node_modules/@types/node
else
  PROFILE_NM="${DSH_PROFILE_NM:-$HOME/.dsh/profiles/web/node_modules}"
  pick() {
    if [ -e "$PROFILE_NM/$1" ]; then echo "$PROFILE_NM/$1"; else echo "$CHECKOUT/node_modules/@deepseek-ai/$2"; fi
  }
  link_pkg @deepseek-ai/dsh-tools "$CHECKOUT/node_modules/@deepseek-ai/dsh-tools"
  link_pkg @deepseek-ai/dsh-llm "$CHECKOUT/node_modules/@deepseek-ai/dsh-llm"
  link_pkg @types/node "$CHECKOUT/node_modules/@types/node"
  link_pkg cordis "$CHECKOUT/node_modules/@deepseek-ai/cordis"
  link_pkg schemastery "$(pick schemastery schemastery)"
  link_pkg cosmokit "$(pick cosmokit cosmokit)"
  STD_SCHEMA=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname '@standard-schema+spec@*' 2>/dev/null | head -1 || true)
  if [ -z "$STD_SCHEMA" ] && [ -e "$CHECKOUT/node_modules/@standard-schema/spec" ]; then
    STD_SCHEMA="$CHECKOUT/node_modules/@standard-schema/spec"
  fi
  if [ -n "$STD_SCHEMA" ]; then
    mkdir -p node_modules/@standard-schema
    ln -sfn "$(cd "$STD_SCHEMA" && pwd)" node_modules/@standard-schema/spec
  fi
fi

echo "=== Compiling src → lib ($TSC) ==="
"$TSC" -p tsconfig.json

if [ -f tsdown.config.ts ] && [ -x "$ROOT/node_modules/.bin/tsdown" ]; then
  echo "=== Building client bundle (tsdown) ==="
  npm run build:client --silent
fi
echo "=== Build complete ==="
